"""empty message

Revision ID: 180099bd454b
Revises: 91248754a45e
Create Date: 2020-03-05 13:50:53.014469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '180099bd454b'
down_revision = '91248754a45e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('genres', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'genres')
    # ### end Alembic commands ###
